### ISSUE TITLE
是否有码表文档可以提供

### ISSUE THREAD

**Issue by saksim** [moeheart/jx3bla#1]
首先非常感谢作者开源自己的代码。使得对了解剑三如何做数据分析非常具有意义。

背景：想动态监测本人的PVP战斗DPS情况，已经能实时将数据放入KAFKA生产消费，但是消费到的数据，并不知晓其数据结构为何种含义。从你提供的parseLuatable函数解析完毕luatable后，各层次比较多。

> **我想请教的是：**
>> **1. 不知道是否有文档，描述每一项是代表的何值【具体而言：16是复盘数据；10是门派数据；9是NPC或者玩家。】**
>> **2. 是否具有一般的结构体【比如各层次之间的关系；等】**

以上疑问是由于基于数据处理时，并没有活得[16]的数据。按照您的文档，16代表的时复盘数据，故而，不知道是否能提供相关文档，或者有任何的URL相关说明，或者码表也可。

不胜感谢

**Comment by moeheart** [comment]
数据的具体格式文档在[这里](https://github.com/tinymins/MY/wiki/MY-Recount-Data-Structure)，茗伊提供的。
复盘中[16]缺失的原因是没有在游戏中正确设置。建议开启一次实时模式，并且按照指引来调整设置即可。
另外复盘文件中并没有敌对玩家之间的信息，这一点可能会很影响PVP相关的场景。

**Comment by saksim** [comment]
> 数据的具体格式文档在[这里](https://github.com/tinymins/MY/wiki/MY-Recount-Data-Structure)，茗伊提供的。
> 复盘中[16]缺失的原因是没有在游戏中正确设置。建议开启一次实时模式，并且按照指引来调整设置即可。
> 另外复盘文件中并没有敌对玩家之间的信息，这一点可能会很影响PVP相关的场景。

感谢回复，问题解决啦~多谢多谢！
