### ISSUE TITLE
可否加个requirements.txt

### ISSUE THREAD

**Issue by NIWA-HOJI** [moeheart/jx3bla#2]
还有我的战斗记录路径是
\JX3\Game\JX3\bin\zhcn_hd\interface\MY#DATA\xxxx@zhcn_hd\userdata\combat_logs

**Comment by moeheart** [comment]
嗷，容我搞搞QAQ

**Comment by Ricardo2001ZG** [comment]
邮箱 ***@***.*** 已收到您的邮件。请等候处理。

**Comment by moeheart** [comment]
好像已经在某次版本更新的时候解决了，虽然可能有新的包没有用到，不过这就是另一个问题了，啊哈哈哈哈哈哈
